import { randomBytes } from "node:crypto";
import { ensureDatabase, sql } from "@/lib/db";
import { hashApiKey } from "@/lib/tam-auth";
import { hashPassword,readSession } from "@/lib/portal-auth";
export const dynamic="force-dynamic";

export async function GET(request:Request){await ensureDatabase();const auth=readSession(request);if(!auth)return Response.json({error:'Authentication required'},{status:401});const clients=auth.role==='client'?await sql`SELECT c.id,c.name,c.status,c.created_at,(SELECT COUNT(*)::int FROM client_companies cc WHERE cc.client_id=c.id) companies,(SELECT COUNT(*)::int FROM tam_contacts tc WHERE tc.client_id=c.id) contacts,(SELECT COUNT(*)::int FROM tam_segments s WHERE s.client_id=c.id) segments FROM clients c WHERE c.id=${auth.clientId} AND c.status='active'`:await sql`SELECT c.id,c.name,c.status,c.created_at,(SELECT COUNT(*)::int FROM client_companies cc WHERE cc.client_id=c.id) companies,(SELECT COUNT(*)::int FROM tam_contacts tc WHERE tc.client_id=c.id) contacts,(SELECT COUNT(*)::int FROM tam_segments s WHERE s.client_id=c.id) segments FROM clients c WHERE c.status='active' ORDER BY CASE WHEN c.name='Venluto' THEN 0 ELSE 1 END,c.name`;return Response.json({clients,canManage:auth.role==='admin'})}
export async function POST(request:Request){await ensureDatabase();const auth=readSession(request);if(auth?.role!=='admin')return Response.json({error:'Admin access required'},{status:403});const body=await request.json() as{name?:string;email?:string;password?:string};const name=body.name?.trim(),email=body.email?.trim().toLowerCase(),password=body.password??'';if(!name||name.length<2||name.length>100)return Response.json({error:"Client name must contain 2 to 100 characters"},{status:400});if(!email||!email.includes('@')||password.length<10)return Response.json({error:'Client email and a temporary password of at least 10 characters are required'},{status:400});if(email===process.env.APP_USER?.trim().toLowerCase())return Response.json({error:'Use a different email. This address is the Venluto administrator account.'},{status:409});const [existingClient]=await sql`SELECT id FROM clients WHERE LOWER(name)=LOWER(${name})`;if(existingClient)return Response.json({error:'A workspace with this name already exists. Delete/archive it before recreating it.'},{status:409});const [existingUser]=await sql`SELECT id FROM workspace_users WHERE LOWER(email)=${email}`;if(existingUser)return Response.json({error:'This email already belongs to another workspace.'},{status:409});const apiKey=`tam_${randomBytes(24).toString('base64url')}`,campaignMatchKeyword=(name.split(/\s+[–—-]\s+/)[0]||name).trim().toLowerCase();const result=await sql.begin(async tx=>{const [client]=await tx`INSERT INTO clients(name,api_key_hash,campaign_match_keyword) VALUES (${name},${hashApiKey(apiKey)},${campaignMatchKeyword}) RETURNING id,name,status,created_at`;await tx`INSERT INTO workspace_users(client_id,email,password_hash) VALUES (${client.id},${email},${hashPassword(password)})`;return client});return Response.json({ok:true,client:result,apiKey,loginEmail:email,warning:"Copy the TAM API key now. It is shown only once."},{status:201})}

export async function PATCH(request:Request){await ensureDatabase();const auth=readSession(request);if(auth?.role!=='admin')return Response.json({error:'Admin access required'},{status:403});const body=await request.json() as{clientId?:number;action?:string};if(body.action!=='rotate_api_key'||!body.clientId)return Response.json({error:'clientId and action rotate_api_key are required'},{status:400});const apiKey=`tam_${randomBytes(24).toString('base64url')}`;const [client]=await sql`UPDATE clients SET api_key_hash=${hashApiKey(apiKey)} WHERE id=${body.clientId} AND status='active' RETURNING id,name`;if(!client)return Response.json({error:'Workspace not found'},{status:404});return Response.json({ok:true,client,apiKey,warning:'The old API key stopped working immediately. Copy this key now.'})}

export async function DELETE(request:Request){await ensureDatabase();const auth=readSession(request);if(auth?.role!=='admin')return Response.json({error:'Admin access required'},{status:403});const body=await request.json() as{clientId?:number;confirmation?:string};const [client]=body.clientId?await sql`SELECT id,name FROM clients WHERE id=${body.clientId}`:[];if(!client)return Response.json({error:'Workspace not found'},{status:404});if(String(client.name).toLowerCase()==='venluto')return Response.json({error:'The primary Venluto workspace cannot be deleted'},{status:400});if(body.confirmation!==client.name)return Response.json({error:'Type the exact workspace name to confirm deletion'},{status:400});await sql.begin(async tx=>{await tx`UPDATE workspace_users SET status='disabled' WHERE client_id=${client.id}`;await tx`UPDATE clients SET status='archived',api_key_hash=NULL WHERE id=${client.id}`});return Response.json({ok:true,message:`${client.name} was removed. Its historical data is preserved.`})}
