import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
test("Railway services and safety defaults are configured",async()=>{const[pkg,env,railway,worker]=await Promise.all([readFile(new URL("../package.json",import.meta.url),"utf8"),readFile(new URL("../.env.example",import.meta.url),"utf8"),readFile(new URL("../railway.json",import.meta.url),"utf8"),readFile(new URL("../worker.mjs",import.meta.url),"utf8")]);assert.match(pkg,/"worker": "node worker\.mjs"/);assert.match(env,/DEMO_MODE=true/);assert.match(railway,/api\/health/);assert.match(worker,/FOR UPDATE SKIP LOCKED/)});
test("List Builder preserves TAM history and uses the real Venluto workspace",async()=>{const[db,tam,ui,env]=await Promise.all([readFile(new URL("../lib/db.ts",import.meta.url),"utf8"),readFile(new URL("../lib/tam.ts",import.meta.url),"utf8"),readFile(new URL("../app/Dashboard.tsx",import.meta.url),"utf8"),readFile(new URL("../.env.example",import.meta.url),"utf8")]);assert.match(db,/CREATE TABLE IF NOT EXISTS client_companies/);assert.match(db,/CREATE TABLE IF NOT EXISTS contact_usage/);assert.match(db,/CREATE TABLE IF NOT EXISTS list_job_steps/);assert.match(tam,/INSERT INTO clients\(name\) VALUES \('Venluto'\)/);assert.doesNotMatch(tam,/ensureDemoTam/);assert.match(ui,/TAM & Segments/);assert.match(env,/TAM_API_KEY=/)});

test("Client portal exposes comparative campaign analytics without sending outreach",async()=>{const[db,analytics,ui]=await Promise.all([readFile(new URL("../lib/db.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/analytics/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/Dashboard.tsx",import.meta.url),"utf8")]);assert.match(db,/CREATE TABLE IF NOT EXISTS campaign_daily_metrics/);assert.match(db,/CREATE TABLE IF NOT EXISTS client_campaigns/);assert.match(analytics,/positiveReply/);assert.match(analytics,/comparison/);assert.match(ui,/Replies \/ Inbox/);assert.match(ui,/Read-only inbox/);assert.match(ui,/Positive reply efficiency/)});
test("TAM imports reconcile, segment and resume without outreach",async()=>{const[db,imports,proxy,ui]=await Promise.all([readFile(new URL("../lib/db.ts",import.meta.url),"utf8"),readFile(new URL("../lib/tam-import.ts",import.meta.url),"utf8"),readFile(new URL("../proxy.ts",import.meta.url),"utf8"),readFile(new URL("../app/Dashboard.tsx",import.meta.url),"utf8")]);assert.match(db,/CREATE TABLE IF NOT EXISTS tam_segments/);assert.match(db,/CREATE TABLE IF NOT EXISTS tam_import_rows/);assert.match(imports,/Matched normalized domain/);assert.match(imports,/possible_duplicate/);assert.match(imports,/ON CONFLICT\(batch_id,row_key\)/);assert.match(imports,/LIMIT \$\{Math\.min/);assert.match(proxy,/TAM_API_KEY/);assert.match(ui,/Claude API ready/);assert.match(ui,/Do not commit until I approve/);assert.doesNotMatch(ui,/type="file"/)});
test("Client TAM workspaces use separate credentials and scoped exports",async()=>{const[db,auth,clients,imports,segments,exportRoute,ui]=await Promise.all([readFile(new URL("../lib/db.ts",import.meta.url),"utf8"),readFile(new URL("../lib/tam-auth.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/clients/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/internal/tam/import/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/internal/tam/segments/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/tam/export/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/Dashboard.tsx",import.meta.url),"utf8")]);assert.match(db,/api_key_hash/);assert.match(auth,/hashApiKey/);assert.match(auth,/WHERE name='Venluto'/);assert.match(clients,/randomBytes\(24\)/);assert.match(imports,/cannot write to the requested client workspace/);assert.match(segments,/sameClient/);assert.match(exportRoute,/clientId is required/);assert.match(ui,/TAM WORKSPACE/);assert.match(ui,/will not show it again/i)});
