import {ensureDatabase,sql} from "@/lib/db";
export const dynamic="force-dynamic";
type RangeKey="7d"|"30d"|"60d"|"all";
const daysFor=(r:RangeKey)=>r==="7d"?7:r==="60d"?60:r==="all"?3650:30;
const pct=(a:number,b:number)=>b===0?(a>0?100:0):Math.round((a-b)/b*1000)/10;
export async function GET(request:Request){
 await ensureDatabase();const url=new URL(request.url),clientId=Number(url.searchParams.get("clientId")),range=(url.searchParams.get("range")??"30d") as RangeKey;
 if(!clientId)return Response.json({error:"clientId is required"},{status:400});const [client]=await sql`SELECT id,name FROM clients WHERE id=${clientId} AND status='active'`;if(!client)return Response.json({error:"Client workspace not found"},{status:404});
 const days=daysFor(range),end=new Date(),start=new Date(end.getTime()-days*86400000),prior=new Date(start.getTime()-days*86400000),startIso=start.toISOString(),endIso=end.toISOString(),priorIso=prior.toISOString();
 await sql`INSERT INTO client_campaigns(client_id,campaign_id,matched_by) SELECT ${clientId},ca.id,'campaign_name' FROM campaigns ca WHERE LOWER(ca.name) LIKE ${`%${String(client.name).toLowerCase()}%`} ON CONFLICT DO NOTHING`;
 const current=await sql`SELECT COALESCE(SUM(people_contacted),0)::int people_contacted,COALESCE(SUM(emails_sent),0)::int emails_sent,COALESCE(SUM(uncontacted_leads),0)::int uncontacted_leads,COALESCE(SUM(replies),0)::int replies,COALESCE(SUM(positive_replies),0)::int positive_replies,COALESCE(SUM(opportunities),0)::int opportunities,COALESCE(SUM(meetings_booked),0)::int meetings_booked,COALESCE(SUM(meetings_completed),0)::int meetings_completed,COALESCE(SUM(closed_won),0)::int closed_won,COALESCE(SUM(revenue_cents),0)::bigint revenue_cents FROM campaign_daily_metrics WHERE client_id=${clientId} AND metric_date>=${startIso}::date AND metric_date<${endIso}::date+1`;
 const priorRows=await sql`SELECT COALESCE(SUM(people_contacted),0)::int people_contacted,COALESCE(SUM(emails_sent),0)::int emails_sent,COALESCE(SUM(uncontacted_leads),0)::int uncontacted_leads,COALESCE(SUM(replies),0)::int replies,COALESCE(SUM(positive_replies),0)::int positive_replies,COALESCE(SUM(opportunities),0)::int opportunities,COALESCE(SUM(meetings_booked),0)::int meetings_booked,COALESCE(SUM(meetings_completed),0)::int meetings_completed,COALESCE(SUM(closed_won),0)::int closed_won,COALESCE(SUM(revenue_cents),0)::bigint revenue_cents FROM campaign_daily_metrics WHERE client_id=${clientId} AND metric_date>=${priorIso}::date AND metric_date<${startIso}::date`;
 const live=async(a:string,b:string)=>(await sql`SELECT COUNT(DISTINCT r.id)::int replies,COUNT(DISTINCT r.id) FILTER(WHERE r.sentiment='positive')::int positive_replies,COUNT(DISTINCT m.id) FILTER(WHERE m.status IN ('confirmed','booked'))::int meetings_booked,COUNT(DISTINCT m.id) FILTER(WHERE m.status IN ('completed','showed'))::int meetings_completed,COUNT(DISTINCT p.id) FILTER(WHERE p.status IN ('closed_won','won'))::int closed_won FROM client_campaigns cc JOIN campaigns ca ON ca.id=cc.campaign_id LEFT JOIN replies r ON r.campaign_id=ca.id AND r.received_at>=${a} AND r.received_at<${b} LEFT JOIN prospects p ON p.id=r.prospect_id LEFT JOIN meetings m ON m.prospect_id=p.id AND m.starts_at>=${a} AND m.starts_at<${b} WHERE cc.client_id=${clientId}`)[0];
 const [nowLive,priorLive]=await Promise.all([live(startIso,endIso),live(priorIso,startIso)]);
 const combine=(r:Record<string,unknown>,l:Record<string,unknown>)=>({peopleContacted:Number(r.people_contacted),emailsSent:Number(r.emails_sent),uncontactedLeads:Number(r.uncontacted_leads),replies:Number(r.replies)+Number(l.replies),positiveReplies:Number(r.positive_replies)+Number(l.positive_replies),opportunities:Number(r.opportunities),meetingsBooked:Number(r.meetings_booked)+Number(l.meetings_booked),meetingsCompleted:Number(r.meetings_completed)+Number(l.meetings_completed),closedWon:Number(r.closed_won)+Number(l.closed_won),revenueCents:Number(r.revenue_cents)});
 let totals=combine(current[0],nowLive),previous=combine(priorRows[0],priorLive);
 const campaigns=await sql`SELECT ca.id,ca.name,ca.external_id,ca.metadata_json->>'status' status,GREATEST(COALESCE((ca.metadata_json->>'people_contacted')::int,0),COALESCE(SUM(dm.people_contacted),0)::int) contacted,GREATEST(COALESCE((ca.metadata_json->>'emails_sent')::int,0),COALESCE(SUM(dm.emails_sent),0)::int) emails_sent,GREATEST(COALESCE((ca.metadata_json->>'uncontacted_leads')::int,0),COALESCE(SUM(dm.uncontacted_leads),0)::int) uncontacted,GREATEST(COALESCE((ca.metadata_json->>'replies')::int,0),COUNT(DISTINCT r.id)::int) replies,GREATEST(COALESCE((ca.metadata_json->>'positive_replies')::int,0),COUNT(DISTINCT r.id) FILTER(WHERE r.sentiment='positive')::int) positive_replies,GREATEST(COALESCE((ca.metadata_json->>'opportunities')::int,0),COALESCE(SUM(dm.opportunities),0)::int) opportunities,COUNT(DISTINCT m.id) FILTER(WHERE m.status IN ('confirmed','booked'))::int booked,COUNT(DISTINCT m.id) FILTER(WHERE m.status IN ('completed','showed'))::int completed,COUNT(DISTINCT p.id) FILTER(WHERE p.status IN ('closed_won','won'))::int closed_won,COALESCE(SUM(dm.revenue_cents),0)::bigint revenue_cents FROM client_campaigns cc JOIN campaigns ca ON ca.id=cc.campaign_id LEFT JOIN campaign_daily_metrics dm ON dm.campaign_id=ca.id AND dm.metric_date>=${startIso}::date AND dm.metric_date<${endIso}::date+1 LEFT JOIN replies r ON r.campaign_id=ca.id AND r.received_at>=${startIso} AND r.received_at<${endIso} LEFT JOIN prospects p ON p.id=r.prospect_id LEFT JOIN meetings m ON m.prospect_id=p.id AND m.starts_at>=${startIso} AND m.starts_at<${endIso} WHERE cc.client_id=${clientId} GROUP BY ca.id ORDER BY positive_replies DESC,ca.name`;
 if(campaigns.length)totals={...totals,peopleContacted:Math.max(totals.peopleContacted,campaigns.reduce((s,c)=>s+Number(c.contacted),0)),emailsSent:Math.max(totals.emailsSent,campaigns.reduce((s,c)=>s+Number(c.emails_sent),0)),uncontactedLeads:Math.max(totals.uncontactedLeads,campaigns.reduce((s,c)=>s+Number(c.uncontacted),0)),replies:Math.max(totals.replies,campaigns.reduce((s,c)=>s+Number(c.replies),0)),opportunities:Math.max(totals.opportunities,campaigns.reduce((s,c)=>s+Number(c.opportunities),0))};
 const inbox=await sql`SELECT r.id,r.body,r.sentiment,r.received_at,p.first_name,p.last_name,p.email,c.name company_name,ca.name campaign_name FROM client_campaigns cc JOIN campaigns ca ON ca.id=cc.campaign_id JOIN replies r ON r.campaign_id=ca.id AND r.sentiment='positive' JOIN prospects p ON p.id=r.prospect_id LEFT JOIN companies c ON c.id=p.company_id WHERE cc.client_id=${clientId} ORDER BY r.received_at DESC LIMIT 250`;
 const comparison=Object.fromEntries(Object.keys(totals).map(k=>[k,pct(totals[k as keyof typeof totals],previous[k as keyof typeof previous])]));
 return Response.json({client,range,totals,comparison,ratios:{positiveReply:totals.positiveReplies?Math.round(totals.peopleContacted/totals.positiveReplies):null,meeting:totals.meetingsBooked?Math.round(totals.emailsSent/totals.meetingsBooked):null},campaigns,inbox,demoMode:process.env.DEMO_MODE!=="false"});
}
