import { ensureDatabase, sql } from "@/lib/db";

export const dynamic = "force-dynamic";
type RangeKey = "7d"|"30d"|"60d"|"all";
const daysFor=(range:RangeKey)=>range==="7d"?7:range==="60d"?60:range==="all"?3650:30;
const pct=(current:number,previous:number)=>previous===0?(current>0?100:0):Math.round(((current-previous)/previous)*1000)/10;

export async function GET(request:Request){
 await ensureDatabase();
 const url=new URL(request.url),clientId=Number(url.searchParams.get("clientId")),range=(url.searchParams.get("range")??"30d") as RangeKey;
 if(!clientId)return Response.json({error:"clientId is required"},{status:400});
 const [client]=await sql`SELECT id,name FROM clients WHERE id=${clientId} AND status='active'`;
 if(!client)return Response.json({error:"Client workspace not found"},{status:404});
 const days=daysFor(range),end=new Date(),start=new Date(end.getTime()-days*86400000),previousStart=new Date(start.getTime()-days*86400000);
 const startIso=start.toISOString(),endIso=end.toISOString(),previousIso=previousStart.toISOString();
 await sql`INSERT INTO client_campaigns(client_id,campaign_id,matched_by) SELECT ${clientId},ca.id,'campaign_name' FROM campaigns ca WHERE LOWER(ca.name) LIKE ${`%${String(client.name).toLowerCase()}%`} ON CONFLICT DO NOTHING`;
 if(String(client.name).toLowerCase()==='venluto')await sql`INSERT INTO client_campaigns(client_id,campaign_id,matched_by) SELECT ${clientId},ca.id,'legacy_venluto' FROM campaigns ca WHERE NOT EXISTS(SELECT 1 FROM client_campaigns cc WHERE cc.campaign_id=ca.id) ON CONFLICT DO NOTHING`;
 const metricRows=await sql`SELECT COALESCE(SUM(people_contacted),0)::int people_contacted,COALESCE(SUM(emails_sent),0)::int emails_sent,COALESCE(SUM(replies),0)::int replies,COALESCE(SUM(positive_replies),0)::int positive_replies,COALESCE(SUM(meetings_booked),0)::int meetings_booked,COALESCE(SUM(meetings_completed),0)::int meetings_completed,COALESCE(SUM(closed_won),0)::int closed_won,COALESCE(SUM(revenue_cents),0)::bigint revenue_cents FROM campaign_daily_metrics WHERE client_id=${clientId} AND metric_date>=${startIso}::date AND metric_date<${endIso}::date+1`;
 const previousRows=await sql`SELECT COALESCE(SUM(people_contacted),0)::int people_contacted,COALESCE(SUM(emails_sent),0)::int emails_sent,COALESCE(SUM(replies),0)::int replies,COALESCE(SUM(positive_replies),0)::int positive_replies,COALESCE(SUM(meetings_booked),0)::int meetings_booked,COALESCE(SUM(meetings_completed),0)::int meetings_completed,COALESCE(SUM(closed_won),0)::int closed_won,COALESCE(SUM(revenue_cents),0)::bigint revenue_cents FROM campaign_daily_metrics WHERE client_id=${clientId} AND metric_date>=${previousIso}::date AND metric_date<${startIso}::date`;
 const [live]=await sql`SELECT COUNT(DISTINCT r.id)::int replies,COUNT(DISTINCT r.id) FILTER(WHERE r.sentiment='positive')::int positive_replies,COUNT(DISTINCT m.id) FILTER(WHERE m.status='confirmed')::int meetings_booked,COUNT(DISTINCT m.id) FILTER(WHERE m.status='completed')::int meetings_completed,COUNT(DISTINCT p.id) FILTER(WHERE p.status IN ('closed_won','won'))::int closed_won FROM client_campaigns cc JOIN campaigns ca ON ca.id=cc.campaign_id LEFT JOIN replies r ON r.campaign_id=ca.id AND r.received_at>=${startIso} AND r.received_at<${endIso} LEFT JOIN prospects p ON p.id=r.prospect_id LEFT JOIN meetings m ON m.prospect_id=p.id AND m.starts_at>=${startIso} AND m.starts_at<${endIso} WHERE cc.client_id=${clientId}`;
 const [previousLive]=await sql`SELECT COUNT(DISTINCT r.id)::int replies,COUNT(DISTINCT r.id) FILTER(WHERE r.sentiment='positive')::int positive_replies,COUNT(DISTINCT m.id) FILTER(WHERE m.status='confirmed')::int meetings_booked,COUNT(DISTINCT m.id) FILTER(WHERE m.status='completed')::int meetings_completed,COUNT(DISTINCT p.id) FILTER(WHERE p.status IN ('closed_won','won'))::int closed_won FROM client_campaigns cc JOIN campaigns ca ON ca.id=cc.campaign_id LEFT JOIN replies r ON r.campaign_id=ca.id AND r.received_at>=${previousIso} AND r.received_at<${startIso} LEFT JOIN prospects p ON p.id=r.prospect_id LEFT JOIN meetings m ON m.prospect_id=p.id AND m.starts_at>=${previousIso} AND m.starts_at<${startIso} WHERE cc.client_id=${clientId}`;
 const combine=(row:Record<string,unknown>,captured:Record<string,unknown>)=>({peopleContacted:Number(row.people_contacted),emailsSent:Number(row.emails_sent),replies:Number(row.replies)+Number(captured.replies),positiveReplies:Number(row.positive_replies)+Number(captured.positive_replies),meetingsBooked:Number(row.meetings_booked)+Number(captured.meetings_booked),meetingsCompleted:Number(row.meetings_completed)+Number(captured.meetings_completed),closedWon:Number(row.closed_won)+Number(captured.closed_won),revenueCents:Number(row.revenue_cents)});
 const totals=combine(metricRows[0],live),previous=combine(previousRows[0],previousLive);
 const campaigns=await sql`SELECT ca.id,ca.name,ca.external_id,COUNT(DISTINCT r.id)::int replies,COUNT(DISTINCT r.id) FILTER(WHERE r.sentiment='positive')::int positive_replies,COUNT(DISTINCT m.id) FILTER(WHERE m.status='confirmed')::int meetings FROM client_campaigns cc JOIN campaigns ca ON ca.id=cc.campaign_id LEFT JOIN replies r ON r.campaign_id=ca.id AND r.received_at>=${startIso} AND r.received_at<${endIso} LEFT JOIN prospects p ON p.id=r.prospect_id LEFT JOIN meetings m ON m.prospect_id=p.id AND m.starts_at>=${startIso} AND m.starts_at<${endIso} WHERE cc.client_id=${clientId} GROUP BY ca.id ORDER BY positive_replies DESC,ca.name`;
 const inbox=await sql`SELECT r.id,r.body,r.sentiment,r.received_at,p.first_name,p.last_name,p.email,c.name company_name,ca.name campaign_name FROM client_campaigns cc JOIN campaigns ca ON ca.id=cc.campaign_id JOIN replies r ON r.campaign_id=ca.id JOIN prospects p ON p.id=r.prospect_id LEFT JOIN companies c ON c.id=p.company_id WHERE cc.client_id=${clientId} ORDER BY r.received_at DESC LIMIT 100`;
 const daily=await sql`SELECT day::date date,COALESCE(SUM(dm.people_contacted),0)::int contacted,COALESCE(SUM(dm.emails_sent),0)::int emails_sent,COALESCE(SUM(dm.positive_replies),0)::int metric_positive,COALESCE(SUM(dm.meetings_booked),0)::int metric_booked FROM generate_series(${startIso}::date,${endIso}::date,'1 day') day LEFT JOIN campaign_daily_metrics dm ON dm.client_id=${clientId} AND dm.metric_date=day GROUP BY day ORDER BY day DESC LIMIT 90`;
 const comparison=Object.fromEntries(Object.keys(totals).map(key=>[key,pct(totals[key as keyof typeof totals],previous[key as keyof typeof previous])]));
 return Response.json({client,range,totals,previous,comparison,ratios:{positiveReply:totals.positiveReplies?Math.round(totals.peopleContacted/totals.positiveReplies):null,meeting:totals.meetingsBooked?Math.round(totals.emailsSent/totals.meetingsBooked):null},campaigns,inbox,daily,demoMode:process.env.DEMO_MODE!=="false"});
}
