import { timingSafeEqual } from "node:crypto";
import { ensureDemoTam, tamDashboard } from "@/lib/tam";
import { sql } from "@/lib/db";
export const dynamic="force-dynamic";
function valid(value:string,expected:string){const a=Buffer.from(value),b=Buffer.from(expected);return a.length===b.length&&timingSafeEqual(a,b)}
export async function GET(request:Request){
 const expected=process.env.TAM_API_KEY;if(!expected)return Response.json({error:"TAM_API_KEY is not configured"},{status:503});
 const auth=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??request.headers.get("x-api-key")??"";if(!valid(auth,expected))return Response.json({error:"Unauthorized"},{status:401});
 const client=await ensureDemoTam(),url=new URL(request.url),resource=url.searchParams.get("resource")??"summary",limit=Math.min(Math.max(Number(url.searchParams.get("limit")??100),1),500),offset=Math.max(Number(url.searchParams.get("offset")??0),0);
 if(resource==="companies"){const rows=await sql`SELECT cc.id,c.name,c.domain,cc.icp_status,cc.icp_reason,cc.attributes_json,sb.provider source_provider,sb.label source_batch FROM client_companies cc JOIN companies c ON c.id=cc.company_id LEFT JOIN source_batches sb ON sb.id=cc.source_batch_id WHERE cc.client_id=${client.id} ORDER BY cc.id LIMIT ${limit} OFFSET ${offset}`;return Response.json({schemaVersion:"2026-09-23",resource,limit,offset,items:rows})}
 if(resource==="contacts"){const rows=await sql`SELECT tc.id,tc.first_name,tc.last_name,tc.title,tc.email,tc.linkedin_url,tc.email_status,tc.eligibility_status,tc.eligibility_reason,tc.verified_at,c.name company_name,c.domain,sb.provider source_provider,(SELECT json_agg(u ORDER BY u.used_at DESC) FROM contact_usage u WHERE u.contact_id=tc.id) prior_use,(SELECT json_agg(d ORDER BY d.decided_at DESC) FROM icp_decisions d WHERE d.contact_id=tc.id) icp_decisions FROM tam_contacts tc JOIN companies c ON c.id=tc.company_id LEFT JOIN source_batches sb ON sb.id=tc.source_batch_id WHERE tc.client_id=${client.id} ORDER BY tc.id LIMIT ${limit} OFFSET ${offset}`;return Response.json({schemaVersion:"2026-09-23",resource,limit,offset,items:rows})}
 if(resource==="job_contacts"){const jobId=Number(url.searchParams.get("job_id")??0);if(!jobId)return Response.json({error:"job_id is required"},{status:400});const rows=await sql`SELECT jc.job_id,jc.contact_id,jc.disposition,jc.reason_code,tc.first_name,tc.last_name,tc.title,tc.email,c.name company_name,c.domain FROM list_job_contacts jc JOIN list_jobs j ON j.id=jc.job_id JOIN tam_contacts tc ON tc.id=jc.contact_id JOIN companies c ON c.id=tc.company_id WHERE j.client_id=${client.id} AND jc.job_id=${jobId} ORDER BY jc.contact_id LIMIT ${limit} OFFSET ${offset}`;return Response.json({schemaVersion:"2026-09-23",resource,jobId,limit,offset,items:rows})}
 const data=await tamDashboard();return Response.json({schemaVersion:"2026-09-23",purpose:"Claude Code-readable client TAM and resumable list jobs",endpoints:["?resource=companies","?resource=contacts","?resource=job_contacts&job_id=ID"],...data})
}
