import { ensureDatabase, sql } from "@/lib/db";
export const dynamic="force-dynamic";
export async function GET(){await ensureDatabase();const [prospects,replies,meetings,errors,tasks]=await Promise.all([
 sql`SELECT p.*,o.name owner_name,o.initials owner_initials,c.name company_name,c.domain company_domain,(SELECT COUNT(*)::int FROM replies r WHERE r.prospect_id=p.id AND LOWER(COALESCE(r.reply_category,'')) IN ('interested','information request','meeting request')) reply_count,(SELECT COUNT(*)::int FROM meetings m WHERE m.prospect_id=p.id AND m.status='confirmed') meeting_count FROM prospects p LEFT JOIN owners o ON o.id=p.owner_id LEFT JOIN companies c ON c.id=p.company_id WHERE EXISTS (SELECT 1 FROM replies r WHERE r.prospect_id=p.id AND LOWER(COALESCE(r.reply_category,'')) IN ('interested','information request','meeting request')) OR p.status IN ('meeting_booked','qualified','showed','completed','no_show','noshow','closed_won','won') ORDER BY p.updated_at DESC`,
 sql`SELECT r.*,p.first_name,p.last_name,p.title,p.deadline_at,p.next_action,p.close_url,o.name owner_name,o.initials owner_initials,c.name company_name,c.domain company_domain,ca.name campaign_name FROM replies r JOIN prospects p ON p.id=r.prospect_id LEFT JOIN owners o ON o.id=p.owner_id LEFT JOIN companies c ON c.id=p.company_id LEFT JOIN campaigns ca ON ca.id=r.campaign_id WHERE LOWER(COALESCE(r.reply_category,'')) IN ('interested','information request','meeting request') AND p.status IN ('replied_positive','action_due') ORDER BY r.received_at DESC`,
 sql`SELECT m.*,p.first_name,p.last_name,c.name company_name,o.name owner_name FROM meetings m LEFT JOIN prospects p ON p.id=m.prospect_id LEFT JOIN companies c ON c.id=p.company_id LEFT JOIN owners o ON o.id=p.owner_id WHERE m.status='confirmed' ORDER BY m.starts_at ASC`,
 sql`SELECT * FROM sync_jobs WHERE status='failed' ORDER BY updated_at DESC`,
 sql`SELECT * FROM operation_tasks WHERE status<>'archived' ORDER BY CASE status WHEN 'open' THEN 0 ELSE 1 END,due_at NULLS LAST,created_at DESC`]);return Response.json({prospects,replies,meetings,errors,tasks,demoMode:process.env.DEMO_MODE!=="false"})}
export async function POST(request:Request){await ensureDatabase();const b=await request.json() as{title?:string;priority?:string;dueAt?:string};if(!b.title?.trim())return Response.json({error:'Task title is required'},{status:400});const [task]=await sql`INSERT INTO operation_tasks(title,priority,due_at) VALUES (${b.title.trim()},${b.priority??'today'},${b.dueAt??null}) RETURNING *`;return Response.json({ok:true,task},{status:201})}
export async function PATCH(request:Request){await ensureDatabase();const b=await request.json() as{taskId?:number;taskStatus?:string;prospectId?:number;ownerId?:number;status?:string;nextAction?:string;deadlineAt?:string;action?:"handled"|"snooze"|"not_relevant"};if(b.taskId){await sql`UPDATE operation_tasks SET status=${b.taskStatus??'done'},updated_at=NOW() WHERE id=${b.taskId}`;return Response.json({ok:true,taskId:b.taskId})}if(!b.prospectId)return Response.json({error:"prospectId is required"},{status:400});const prospectId=b.prospectId;if(b.action){const [p]=await sql`SELECT status FROM prospects WHERE id=${prospectId}`;if(!p)return Response.json({error:"Prospect not found"},{status:404});const next=b.action==="handled"?"handled":b.action==="not_relevant"?"not_relevant":"action_due",reason=b.action==="handled"?"Reply handled":b.action==="not_relevant"?"Marked not relevant / OOO":"Snoozed for one day";await sql.begin(async tx=>{if(b.action==="snooze")await tx`UPDATE prospects SET status='action_due',next_action='Follow up after snooze',deadline_at=NOW()+INTERVAL '1 day',updated_at=NOW() WHERE id=${prospectId}`;else await tx`UPDATE prospects SET status=${next},next_action=NULL,deadline_at=NULL,updated_at=NOW() WHERE id=${prospectId}`;await tx`INSERT INTO prospect_transitions(prospect_id,from_status,to_status,reason) VALUES (${prospectId},${p.status},${next},${reason})`});return Response.json({ok:true,action:b.action})}const [p]=await sql`SELECT status FROM prospects WHERE id=${prospectId}`;if(!p)return Response.json({error:"Prospect not found"},{status:404});await sql.begin(async tx=>{await tx`UPDATE prospects SET owner_id=COALESCE(${b.ownerId??null},owner_id),status=COALESCE(${b.status??null},status),next_action=COALESCE(${b.nextAction??null},next_action),deadline_at=COALESCE(${b.deadlineAt??null},deadline_at),updated_at=NOW() WHERE id=${prospectId}`;if(b.status&&b.status!==p.status)await tx`INSERT INTO prospect_transitions(prospect_id,from_status,to_status,reason) VALUES (${prospectId},${p.status},${b.status},'Moved in Venluto OS CRM')`});return Response.json({ok:true})}
