import {ensureDatabase,sql} from "@/lib/db";
import {readSession,scopedClientId} from "@/lib/portal-auth";
export const dynamic="force-dynamic";
const categories=['interested','information request','meeting request'];

async function ownsProspect(clientId:number,prospectId:number){const [row]=await sql`SELECT p.id FROM prospects p WHERE p.id=${prospectId} AND EXISTS(SELECT 1 FROM replies r JOIN client_campaigns cc ON cc.campaign_id=r.campaign_id JOIN campaigns ca ON ca.id=r.campaign_id JOIN clients cl ON cl.id=cc.client_id WHERE r.prospect_id=p.id AND cc.client_id=${clientId} AND LOWER(ca.name) LIKE '%'||LOWER(cl.name)||'%')`;return Boolean(row)}

export async function GET(request:Request){await ensureDatabase();const clientId=scopedClientId(request,Number(new URL(request.url).searchParams.get('clientId')));if(!clientId)return Response.json({error:'Workspace access denied'},{status:403});const auth=readSession(request);await sql`INSERT INTO client_campaigns(client_id,campaign_id,matched_by) SELECT ${clientId},ca.id,'campaign_name' FROM campaigns ca JOIN clients cl ON cl.id=${clientId} WHERE LOWER(ca.name) LIKE '%'||LOWER(cl.name)||'%' ON CONFLICT DO NOTHING`;const [prospects,replies,meetings,errors,tasks]=await Promise.all([
 sql`SELECT p.*,o.name owner_name,o.initials owner_initials,c.name company_name,c.domain company_domain,(SELECT COUNT(*)::int FROM replies r WHERE r.prospect_id=p.id AND LOWER(COALESCE(r.reply_category,''))=ANY(${categories})) reply_count,(SELECT COUNT(*)::int FROM meetings m WHERE m.prospect_id=p.id AND m.status='confirmed') meeting_count FROM prospects p LEFT JOIN owners o ON o.id=p.owner_id LEFT JOIN companies c ON c.id=p.company_id WHERE EXISTS(SELECT 1 FROM replies r JOIN client_campaigns cc ON cc.campaign_id=r.campaign_id JOIN campaigns ca ON ca.id=r.campaign_id JOIN clients cl ON cl.id=cc.client_id WHERE r.prospect_id=p.id AND cc.client_id=${clientId} AND LOWER(ca.name) LIKE '%'||LOWER(cl.name)||'%') ORDER BY p.updated_at DESC`,
 sql`SELECT r.*,p.first_name,p.last_name,p.title,p.deadline_at,p.next_action,p.close_url,o.name owner_name,o.initials owner_initials,c.name company_name,c.domain company_domain,ca.name campaign_name FROM replies r JOIN client_campaigns cc ON cc.campaign_id=r.campaign_id AND cc.client_id=${clientId} JOIN prospects p ON p.id=r.prospect_id LEFT JOIN owners o ON o.id=p.owner_id LEFT JOIN companies c ON c.id=p.company_id JOIN campaigns ca ON ca.id=r.campaign_id JOIN clients cl ON cl.id=cc.client_id WHERE LOWER(ca.name) LIKE '%'||LOWER(cl.name)||'%' AND LOWER(COALESCE(r.reply_category,''))=ANY(${categories}) AND p.status IN ('replied_positive','action_due') ORDER BY r.received_at DESC`,
 sql`SELECT m.*,p.first_name,p.last_name,c.name company_name,o.name owner_name FROM meetings m LEFT JOIN prospects p ON p.id=m.prospect_id LEFT JOIN companies c ON c.id=p.company_id LEFT JOIN owners o ON o.id=p.owner_id WHERE m.status='confirmed' AND EXISTS(SELECT 1 FROM replies r JOIN client_campaigns cc ON cc.campaign_id=r.campaign_id JOIN campaigns ca ON ca.id=r.campaign_id JOIN clients cl ON cl.id=cc.client_id WHERE r.prospect_id=p.id AND cc.client_id=${clientId} AND LOWER(ca.name) LIKE '%'||LOWER(cl.name)||'%') ORDER BY m.starts_at ASC`,
 auth?.role==='admin'?sql`SELECT * FROM sync_jobs WHERE status='failed' ORDER BY updated_at DESC`:Promise.resolve([]),
 sql`SELECT * FROM operation_tasks WHERE client_id=${clientId} AND status<>'archived' ORDER BY CASE status WHEN 'open' THEN 0 ELSE 1 END,due_at NULLS LAST,created_at DESC`
 ]);return Response.json({prospects,replies,meetings,errors,tasks,demoMode:process.env.DEMO_MODE!=="false"})}

export async function POST(request:Request){await ensureDatabase();const b=await request.json() as{clientId?:number;title?:string;priority?:string;dueAt?:string};const clientId=scopedClientId(request,Number(b.clientId));if(!clientId)return Response.json({error:'Workspace access denied'},{status:403});if(!b.title?.trim())return Response.json({error:'Task title is required'},{status:400});const [task]=await sql`INSERT INTO operation_tasks(client_id,title,priority,due_at) VALUES (${clientId},${b.title.trim()},${b.priority??'today'},${b.dueAt??null}) RETURNING *`;return Response.json({ok:true,task},{status:201})}

export async function PATCH(request:Request){await ensureDatabase();const b=await request.json() as{clientId?:number;taskId?:number;taskStatus?:string;prospectId?:number;ownerId?:number;status?:string;nextAction?:string;deadlineAt?:string;dealValueCents?:number;expectedCloseDate?:string|null;action?:"handled"|"snooze"|"not_relevant"};const clientId=scopedClientId(request,Number(b.clientId));if(!clientId)return Response.json({error:'Workspace access denied'},{status:403});if(b.taskId){await sql`UPDATE operation_tasks SET status=${b.taskStatus??'done'},updated_at=NOW() WHERE id=${b.taskId} AND client_id=${clientId}`;return Response.json({ok:true,taskId:b.taskId})}if(!b.prospectId||!await ownsProspect(clientId,b.prospectId))return Response.json({error:'Prospect not found in this workspace'},{status:404});const prospectId=b.prospectId,[p]=await sql`SELECT status FROM prospects WHERE id=${prospectId}`;if(b.action){const next=b.action==='handled'?'handled':b.action==='not_relevant'?'not_relevant':'action_due',reason=b.action==='handled'?'Reply handled':b.action==='not_relevant'?'Marked not relevant / OOO':'Snoozed for one day';await sql.begin(async tx=>{if(b.action==='snooze')await tx`UPDATE prospects SET status='action_due',next_action='Follow up after snooze',deadline_at=NOW()+INTERVAL '1 day',updated_at=NOW() WHERE id=${prospectId}`;else await tx`UPDATE prospects SET status=${next},next_action=NULL,deadline_at=NULL,updated_at=NOW() WHERE id=${prospectId}`;await tx`INSERT INTO prospect_transitions(prospect_id,from_status,to_status,reason) VALUES (${prospectId},${p.status},${next},${reason})`});return Response.json({ok:true,action:b.action})}
if(b.dealValueCents!==undefined){const cents=Math.round(Number(b.dealValueCents)),date=b.expectedCloseDate?.trim()||null;if(!Number.isFinite(cents)||cents<0)return Response.json({error:'Contract value must be a positive number'},{status:400});if(date&&!/^\d{4}-\d{2}-\d{2}$/.test(date))return Response.json({error:'Expected close date is invalid'},{status:400});const[prospect]=await sql`UPDATE prospects SET deal_value_cents=${cents},expected_close_date=${date}::date,updated_at=NOW() WHERE id=${prospectId} RETURNING id,deal_value_cents,expected_close_date`;return Response.json({ok:true,prospect})}
const prospect=await sql.begin(async tx=>{const[updated]=await tx`UPDATE prospects SET owner_id=COALESCE(${b.ownerId??null},owner_id),status=COALESCE(${b.status??null},status),next_action=COALESCE(${b.nextAction??null},next_action),deadline_at=COALESCE(${b.deadlineAt??null},deadline_at),closed_at=CASE WHEN ${b.status??null} IN ('closed_won','won') THEN COALESCE(closed_at,NOW()) WHEN ${b.status??null} IS NOT NULL THEN NULL ELSE closed_at END,updated_at=NOW() WHERE id=${prospectId} RETURNING *`;if(b.status&&b.status!==p.status)await tx`INSERT INTO prospect_transitions(prospect_id,from_status,to_status,reason) VALUES (${prospectId},${p.status},${b.status},'Moved in Venluto OS CRM')`;return updated});if(!prospect)return Response.json({error:'Lead update did not persist'},{status:409});return Response.json({ok:true,prospect})}
